version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    formatter: simple
    filename: clembench.log
    encoding: utf8
loggers:
  benchmark.run:
    handlers: [ console ]
  backends:
    level: DEBUG
    handlers: [ console ]
  benchmark:
    level: DEBUG
  games:
    level: INFO
  games.wordle.master:
    level: ERROR
root:
  level: INFO
  handlers: [ file_handler ]